### ISSUE TITLE
UserInfo - Put

### ISSUE THREAD

**Issue by y123ob** [jtjun/DutchBroomstick#63]
UserInfo의 Put(Info change)가 없습니다.

**Comment by jtjun** [comment]
def save(self, **kwargs):
        try:
            profile_data = self.validated_data.pop('profile')
        except KeyError:
            profile_data = {}
            
        instance = super.save(**kwargs)
        Profile.objects.update_or_create(user=instance, **profile_data)
        return instance

**Comment by jtjun** [comment]
def update(self, instance, validated_data):
        try:
            profile_data = validated_data.pop('profile')
        except KeyError:
            profile_data = {}

        try:
            password = validated_data.pop('password')
            instance.set_pasword(password)
        except KeyError:
            pass
        
        instance.save(**validated_data)
        
        Profile.objects.update_or_create(user=instance, **profile_data)
        return instance
